---
title: "Shiny.Rmd"
output: html_document
author: "Julia Mateski"
date: "2023-11-03"
---
```{r}
library(shinydashboard)
library(shiny)
library(plotly)
library(tidyverse)
library(ncrmp.benthics.analysis)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(egg)
library(leaflet)
library(leaflet.extras)

source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/Cover.R")
source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/plot_bleaching_prev.R")
source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/Theme.R")
source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/MakeSizeBins.R")
source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/CoralBarChart.R")
source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/SizeFreqUI.R")
source("/Users/juliamateski/Documents/GitHub/NCRMP-Benthic-Shiny/Shiny/habitat.R")



ui <- dashboardPage(
  
  # Dashboard header
  dashboardHeader(title = "Options"),
  
  # Dashboard sidebar with menu items
  dashboardSidebar(
    sidebarMenu(
      id = "tabs",
      menuItem("Size Frequency", tabName = "size_frequency"),
      menuItem("Bleaching", tabName = "bleaching"),
      menuItem("Benthic Community Assessment", tabName = "benthic_cover"),
      menuItem("Coral Demographic Data", tabName = "coral_demographics"),
      menuItem("Map", tabName = "leaflet"),
      

      conditionalPanel(
        condition = 'input.tabs == "size_frequency"', 
      
        selectInput("freq_region", "Select Region:", 
                    choices = c("SEFCRI", "FLK", "Tortugas", "GOM", "PRICO", 
                                "STTSTJ", "STX"),
                    selected = "SEFCRI"),

        uiOutput("speciesSizeFreq") 
      ),
      
      
      
      
         conditionalPanel(
        condition = 'input.tabs == "benthic_cover"',
        checkboxGroupInput("cover", "choose cover", choices = c("CCA", "HARD CORALS", "MACROALGAE", "RAMICRUSTA SPP.", "SOFT CORALS", "SPONGES", "TURF ALGAE", "OTHER"), selected = c("HARD CORALS", "MACROALGAE")),
        sliderInput("year", "Select Year:", min = 2014, max = 2022, value = c(2014, 2022), step = 1),
        checkboxGroupInput("region", "Region", choices = c("Dry Tortugas", "Southeast Florida", "Florida Keys", "Flower Gardens", "Puerto Rico", "St Thomas, St John", "St Croix"), selected = c("Dry Tortugas", "Southeast Florida", "Florida Keys", "Flower Gardens", "Puerto Rico", "St Thomas, St John", "St Croix")),
      ),
            conditionalPanel(
        condition = 'input.tabs == "coral_demographics"',
        checkboxGroupInput("coral_species", "Coral Species", choices = c(
          "Acropora cervicornis",
          "Acropora palmata",
          "Orbicella annularis",
          "Orbicella franksi",
          "Orbicella faveolata",
          "Meandrina meandrites",
          "Dendrogyra cylindrus",
          "Pseudodiploria strigosa",
          "Diploria labyrinthiformis",
          "Colpophyllia natans",
          "Siderastrea siderea",
          "Porites astreoides",
          "Montastraea cavernosa",
          "Agaricia agaricites",
          "Stephanocoenia intersepta"
        ), selected = c(
         "Porites astreoides",
         "Montastraea cavernosa",
          "Orbicella faveolata")),
        selectInput("coral_year", "Year", choices = c( 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022), selected = 2022),
    
        selectInput("coral_region", "Region", choices = c("Dry Tortugas", "Southeast Florida", "Florida Keys", "Flower Gardens", "Puerto Rico", "St Thomas, St John", "St Croix"), selected = "Dry Tortugas")
      ),
      
      conditionalPanel(
        condition = 'input.tabs == "leaflet"', 
        selectInput("map_region", "Select Region:",
                    choices = c("Southeast Florida", "Florida Keys", "Dry Tortugas", "FGBNMS", "PRICO", "STTSTJ", "STX"),
                    selected = "Florida Keys"),
        checkboxGroupInput("year_selector", "Select Year(s)", 
                           choices = 2014:2022, 
                           selected = 2014:2022)
      
      ),
      conditionalPanel(
        condition = 'input.tabs == "bleaching"', 
        selectInput("health_region", "Select Region:", 
                    choices = c("Southeast Florida", "Florida Keys", "Dry Tortugas", 
                                "Flower Gardens", "Puerto Rico", "St Thomas, St John", 
                                "St Croix"), selected = "FLK"),
        selectInput("health_year", "Select Year", 
                    choices = c(2013:2022), selected = 2022),
        uiOutput("speciesSelect")  
      )
    )
  ),
  

  dashboardBody(
    tabItems(
      

      tabItem(
        tabName = "size_frequency",
        h2("Size Frequency"),
        fluidRow(
        plotOutput("size_freq"),
        p("Relative length (maximum coral diameter) frequency (bars) and percentage of old mortality (lines, points) by colony size of select coral species in specific sampling years. Note: gaps in lines indicate no data for specific year (color) and size class. Note: y-axis scale relates to both relative length frequency and percentage of old mortality (*100).")
        )
        ),
      

      tabItem(
        tabName = "bleaching",
        h2("Bleaching and Disease"),
        fluidRow(
          plotOutput("bleach"),
          plotOutput("disease"),
          p("Mean disease prevalence (left) and bleaching prevalence (right) ± SE by coral species for St. Thomas- St. John in 2023. The number of coral colonies surveyed by species are in parentheses. Only species with disease or bleaching observed in the 2023 NCRMP demographics surveys are included. Note: species are sorted in order of decreasing bleaching prevalence, and x-axis scale varies by metric.")
        )
      ),
      

      tabItem(
        tabName = "benthic_cover",
        h2("% Cover of Benthic Communities"),
        fluidRow(
          box(title = "Dry Tortugas", plotOutput("dry_tortugas_plot", height = 400)),
          box(title = "Southeast Florida", plotOutput("southeast_florida_plot", height = 400)),
          box(title = "Florida Keys", plotOutput("florida_keys_plot", height = 400)),
          box(title = "Flower Gardens", plotOutput("flower_gardens_plot", height = 400)),
          box(title = "Puerto Rico", plotOutput("puerto_rico_plot", height = 400)),
          box(title = "St Thomas, St John", plotOutput("st_thomas_st_john_plot", height = 400)),
          box(title = "St Croix", plotOutput("st_croix_plot", height = 400)),
          p("Overall cover (%) for benthic cover type for each region from NCRMP surveys. Statistical significance (Tukey’s two-tailed t-test), if present, is reported at p <0.05, and different letters (e.g., a and b) denote a difference between survey years. SE = standard error.")
        )
      ),
      

      tabItem(
        tabName = "coral_demographics",
        h2("Coral Demographics"),
        fluidRow(
          plotOutput("coral_plot"),
          p("Mean density of corals (colonies/m2), maximum diameter (cm), percentage of old mortality (%), and percentage of recent mortality (%) by coral species. Species are ordered in terms of decreasing density, and only species with densities above 0.01 are included.")
        )
      ),
      

      tabItem(
        tabName = "leaflet",
        h2("Leaflet"),
        fluidRow(
          leafletOutput("map"),
          p("Map of coral data by region and year input")
        )
      )
    )
  )
)

```


```{r #server}
server <- function(input, output) {

  
habitat_lookup <- data.frame(
  REGION = c("FLK", "FLK", "FLK", "FLK", "FLK", "FLK", "FLK", "FLK", "FLK",
             "Tortugas", "Tortugas", "Tortugas", "Tortugas", "Tortugas", "Tortugas", "Tortugas", "Tortugas", "Tortugas",
             "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI", "SEFCRI"),
  HABITAT_CD = c(
    "CONT_HR", "CONT_LR", "CONT_MR", "ISOL_HR", "ISOL_LR", "ISOL_MR", "RUBB_LR", "SPGR_HR", "SPGR_MR",
    "CONT_HR", "CONT_LR", "CONT_MR", "ISOL_HR", "ISOL_LR", "ISOL_MR", "RUBB_LR", "SPGR_HR", "SPGR_MR",
    "APRD", "CPDP", "CPSH", "DPRC", "LIRI", "LIRM", "LIRO", "PTCH", "RGDP", "RGSH", "SCRS", "SPGR"),
  HABITAT_TYPE = c(
    "Contiguous reef, non-spur-groove, high vertical relief",
    "Contiguous reef, non-spur-groove, low vertical relief",
    "Contiguous reef, non-spur-groove, moderate vertical relief",
    "Isolated, patchy reef structures, high vertical relief",
    "Isolated, patchy reef structures, low vertical relief",
    "Isolated, patchy reef structures, moderate vertical relief",
    "Reef rubble, low vertical relief",
    "Spur-groove reef, high vertical relief",
    "Spur-groove reef, moderate vertical relief",
    "Contiguous reef, non-spur-groove, high vertical relief",
    "Contiguous reef, non-spur-groove, low vertical relief",
    "Contiguous reef, non-spur-groove, moderate vertical relief",
    "Isolated, patchy reef structures, high vertical relief",
    "Isolated, patchy reef structures, low vertical relief",
    "Isolated, patchy reef structures, moderate vertical relief",
    "Reef rubble, low vertical relief",
    "Spur-groove reef, high vertical relief",
    "Spur-groove reef, moderate vertical relief",
    "Aggregated Patch Reef Deep",
    "Colonized Pavement Deep",
    "Colonized Pavement Shallow",
    "Deep Ridge Complex",
    "Linear Reef Inner",
    "Linear Reef Middle",
    "Linear Reef Outer",
    "Patch Reef",
    "Ridge Deep",
    "Ridge Shallow",
    "Scattered Coral and Rock in Sand",
    "Spur and Groove")
)

SEFCRI_leaf <- full_join(NCRMP_SEFCRI_2014_22_density_site, NCRMP_SEFCRI_2014_22_cover_region)%>%
      distinct(PRIMARY_SAMPLE_UNIT, .keep_all = TRUE) %>%
      select(REGION, PRIMARY_SAMPLE_UNIT, YEAR, HABITAT_CD, LAT_DEGREES, LON_DEGREES, DENSITY, avCvr) %>%
      mutate(across(c(LAT_DEGREES, LON_DEGREES), as.numeric)) %>%
      left_join(habitat_lookup, by = c("REGION", "HABITAT_CD"))

TORT_leaf <- full_join(NCRMP_Tort_2014_22_density_site, NCRMP_Tort_2014_22_cover_region)%>%
      distinct(PRIMARY_SAMPLE_UNIT, .keep_all = TRUE) %>%
      select(REGION, PRIMARY_SAMPLE_UNIT, YEAR, HABITAT_CD, LAT_DEGREES, LON_DEGREES, DENSITY, avCvr) %>%
      mutate(across(c(LAT_DEGREES, LON_DEGREES), as.numeric)) %>%
      left_join(habitat_lookup, by = c("REGION", "HABITAT_CD"))

KEYS_leaf <- full_join(NCRMP_FLK_2014_22_density_site, NCRMP_FLK_2014_22_cover_region) %>%
      distinct(PRIMARY_SAMPLE_UNIT, .keep_all = TRUE) %>%
      select(REGION, PRIMARY_SAMPLE_UNIT, YEAR, HABITAT_CD, LAT_DEGREES, LON_DEGREES, DENSITY, avCvr) %>%
      mutate(across(c(LAT_DEGREES, LON_DEGREES), as.numeric)) %>%
      left_join(habitat_lookup, by = c("REGION", "HABITAT_CD"))

FGBNMS_leaf <- full_join(NCRMP_FGBNMS_2013_22_density_site, NCRMP_FGBNMS_2013_22_cover_region)%>%
      distinct(PRIMARY_SAMPLE_UNIT, .keep_all = TRUE) %>%
      select(REGION, PRIMARY_SAMPLE_UNIT, YEAR, HABITAT_CD, LAT_DEGREES, LON_DEGREES, DENSITY, avCvr) %>%
      mutate(across(c(LAT_DEGREES, LON_DEGREES), as.numeric)) %>%
      left_join(habitat_lookup, by = c("REGION", "HABITAT_CD"))

PRICO_leaf <-  full_join(NCRMP_PRICO_2014_21_density_site, NCRMP_PRICO_2014_21_cover_region)%>%
      distinct(PRIMARY_SAMPLE_UNIT, .keep_all = TRUE) %>%
      select(REGION, PRIMARY_SAMPLE_UNIT, YEAR, HABITAT_CD, LAT_DEGREES, LON_DEGREES, DENSITY, avCvr) %>%
      mutate(across(c(LAT_DEGREES, LON_DEGREES), as.numeric)) %>%
      left_join(habitat_lookup, by = c("REGION", "HABITAT_CD"))

STTSTJ_leaf <-  full_join(NCRMP_STTSTJ_2013_21_density_site, NCRMP_STTSTJ_2013_21_cover_region) %>%
      distinct(PRIMARY_SAMPLE_UNIT, .keep_all = TRUE) %>%
      select(REGION, PRIMARY_SAMPLE_UNIT, YEAR, HABITAT_CD, LAT_DEGREES, LON_DEGREES, DENSITY, avCvr) %>%
      mutate(across(c(LAT_DEGREES, LON_DEGREES), as.numeric)) %>%
      left_join(habitat_lookup, by = c("REGION", "HABITAT_CD"))
 
  
  
output$speciesSizeFreq <- renderUI({
    req(input$freq_region)
    species_choices <- size_freq(input$freq_region)
    selectInput("speciesSizeFreq", "Select Species:", choices = species_choices)
  })



  
output$size_freq <- renderPlot({
  
  region_years <- list(
    'FLK' = c(2014, 2018, 2022),
    'SEFCRI' = c(2014, 2018, 2022),
    'Tortugas' = c(2014, 2018, 2022),
    'PRICO' = c(2014, 2021),
    'STX' = c(2015, 2021),
    'STTSTJ' = c(2013, 2021),
    'GOM' = c(2018, 2022)
  )

   spp1 <- input$speciesSizeFreq
   
   tmp <- NCRMP_make_size_bins(region = input$freq_region, project = "NCRMP", years = region_years[[input$freq_region]])
    
    
    domain_sub <- tmp$length_freq_domain_est %>%
      mutate(YEAR = ifelse(YEAR == "2020", "2021", as.character(YEAR))) %>%
      mutate(YEAR = as.factor(YEAR)) %>%
      subset(SPECIES_NAME == spp1)
    
    demos_sub <- tmp$length_demos %>%
      mutate(YEAR = ifelse(YEAR == "2020", "2021", as.character(YEAR))) %>%
      mutate(YEAR = as.factor(YEAR)) %>%
      subset(SPECIES_NAME == spp1)
    
    domain_sub <- domain_sub %>%
      tidyr::expand(., REGION, SPECIES_NAME, SPECIES_CD, YEAR, bin_num) %>%
      dplyr::full_join(., domain_sub, by = c('REGION', 'SPECIES_NAME',"SPECIES_CD", "YEAR", "bin_num")) %>%
      dplyr::mutate(length_freq_domain = ifelse(is.na(length_freq_domain), 0, length_freq_domain))
    

    n_bins <- max(demos_sub$n_bins)
    text_size = 14
    angle = 45
    hjust = 1
    
    min <- min(demos_sub$min)
    bin_width <- min(demos_sub$bin_width)
    
    lab_vec = c(" 4- 10", " 11-15", " 16-20", " 21-25", " 26-30", " 31-35", " 36-45", " 46-65", " 66-85", " 86-105", "106+")
    
    p1 <- ggplot(data = domain_sub, 
                 aes(x = as.integer(bin_num),
                     y = length_freq_domain, fill = YEAR)) +
      geom_bar(stat="identity", position = "dodge2", width = .9, color="black", size=.5) +
      theme_minimal() + 
      facet_wrap(~SPECIES_NAME) +
      labs(y = "Length (cm)", x = "") +
      scale_x_continuous(breaks = seq_along(lab_vec), labels = lab_vec) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
      ggtitle(input$freq_region) +
      theme(axis.text.x = element_text(size = text_size, angle = angle, hjust = hjust),
            strip.text = element_text(face = "italic")) +
      scale_fill_manual(values=c('deepskyblue4','springgreen3','gold1')) +
      scale_color_manual(values=c('deepskyblue4','springgreen3','gold1'))
    
    print(p1)
  }) 
    





output$map <- renderLeaflet({ #start leaflet
 
 data <- reactive({
    if (input$map_region == "Southeast Florida") {
      SEFCRI_leaf
    } else if (input$map_region == "Dry Tortugas") {
      TORT_leaf
    } else if (input$map_region == "Florida Keys") {
      KEYS_leaf
    } else if (input$map_region == "FGBNMS") {
      FGBNMS_leaf
    } else if (input$map_region == "PRICO") {
      PRICO_leaf
    } else if (input$map_region == "STTSTJ") {
      STTSTJ_leaf
    }
    })
  

  leaflet_map <- leaflet(data()) %>%
    addProviderTiles(providers$Esri.OceanBasemap) %>%
    addCircleMarkers(
      lat = ~LAT_DEGREES,
      lng = ~LON_DEGREES,
      radius = 5,
      fillOpacity = 0.8,
      fillColor = ~colorFactor(as.factor(YEAR), palette = "Set3"),
      stroke = FALSE,
      popup = ~paste(
        "Year: ", YEAR, "<br>",
        "Habitat Code: ", HABITAT_CD, "<br>",
        "Habitat Type: ", HABITAT_TYPE, "<br>",
        "Total Coral Density: ", DENSITY, "<br>",
        "Total Hard Coral Cover: ", round(avCvr, 2)
      )
    ) 


  leaflet_map
  
}) #end leaflet
  
  
  
output$coral_plot <- renderPlot({
    
    selected_region <- input$coral_region
    selected_year <- as.character(input$coral_year)
    species_list <- input$coral_species
  
    
    if (selected_region == "Dry Tortugas") {
      
      Tort_weightedmeans <- NCRMP_Tort_Occ_Den_CV
      #, YEAR == max(NCRMP_Tort_Occ_Den_CV$YEAR)) 
 
      om <- NCRMP_DRM_calculate_mortality(region = "Tortugas", project = "NCRMP_DRM")
      Tort_om_spp <- om$Domain_est_old_mort_species
      Tort_rm_spp <- om$Domain_est_rec_mort_species
  
      s <- NCRMP_DRM_calculate_mean_colony_size(region = "Tortugas", project = "NCRMP_DRM")
      Tort_s_spp <- s$Domain_est_species
      
      generateCoralPlot("Dry Tortugas", selected_year, Tort_weightedmeans,Tort_om_spp, Tort_s_spp, Tort_rm_spp, species_list)
    }
    
    
    else if (selected_region == "Southeast Florida") {
  SEFL_weightedmeans <- NCRMP_DRM_SEFCRI_Occ_Den_CV
    #filter(YEAR == max(YEAR, na.rm = TRUE))
  
  om <- NCRMP_DRM_calculate_mortality(region = "SEFCRI", project = "NCRMP_DRM")
  SEFL_om_spp <- om$Domain_est_old_mort_species
  SEFL_rm_spp <- om$Domain_est_rec_mort_species
  
  s <- NCRMP_DRM_calculate_mean_colony_size(region = "SEFCRI", project = "NCRMP_DRM")
  SEFL_s_spp <- s$Domain_est_species
  
  generateCoralPlot("Southeast Florida", selected_year, SEFL_weightedmeans, SEFL_om_spp, SEFL_s_spp, SEFL_rm_spp, species_list)
}
    
    
    else if (selected_region == "Florida Keys") {
      FLK_weightedmeans <- NCRMP_DRM_FLK_Occ_Den_CV
      #, YEAR == max(NCRMP_DRM_FLK_Occ_Den_CV$YEAR))
      om <- NCRMP_DRM_calculate_mortality(region = "FLK", project = "NCRMP_DRM")
      FLK_om_spp <- om$Domain_est_old_mort_species
      FLK_rm_spp <- om$Domain_est_rec_mort_species
      
      # load species specific size - using max diameter here because DRM doesn't collect what's needed for area or volume
      # note this is not standardized by mortality though***
      s <- NCRMP_DRM_calculate_mean_colony_size(region = "FLK", project = "NCRMP_DRM")
      FLK_s_spp <- s$Domain_est_species
      generateCoralPlot("Florida Keys",selected_year, FLK_weightedmeans, FLK_om_spp, FLK_s_spp, FLK_rm_spp, species_list)
    }
    
     else if (selected_region == "Puerto Rico") {
      PRICO_weightedmeans <- NCRMP_PRICO_Occ_Den_CV
      #, YEAR == max(NCRMP_DRM_FLK_Occ_Den_CV$YEAR))
      om <- NCRMP_DRM_calculate_mortality(region = "PRICO", project = "NCRMP")
      PRICO_om_spp <- om$Domain_est_old_mort_species
      PRICO_rm_spp <- om$Domain_est_rec_mort_species
      
      # load species specific size - using max diameter here because DRM doesn't collect what's needed for area or volume
      # note this is not standardized by mortality though***
      s <- NCRMP_DRM_calculate_mean_colony_size(region = "PRICO", project = "NCRMP")
      PRICO_s_spp <- s$Domain_est_species
      generateCoralPlot("Puerto Rico",selected_year, PRICO_weightedmeans, PRICO_om_spp, PRICO_s_spp, PRICO_rm_spp, species_list)
     }
    
    #"SEFCRI", "FLK", "Tortugas", "FGBNMS", "PRICO", "STTSTJ", "STX")
    
     else if (selected_region == "Flower Gardens") {
      FGBNMS_weightedmeans <- NCRMP_FGBNMS_Occ_Den_CV
      #, YEAR == max(NCRMP_DRM_FLK_Occ_Den_CV$YEAR))
      om <- NCRMP_DRM_calculate_mortality(region = "FGBNMS", project = "NCRMP")
      FGBNMS_om_spp <- om$Domain_est_old_mort_species
      FGBNMS_rm_spp <- om$Domain_est_rec_mort_species
      
      # load species specific size - using max diameter here because DRM doesn't collect what's needed for area or volume
      # note this is not standardized by mortality though***
      s <- NCRMP_DRM_calculate_mean_colony_size(region = "FGBNMS", project = "NCRMP")
      FGBNMS_s_spp <- s$Domain_est_species
      generateCoralPlot("Flower Gardens",selected_year, FGBNMS_weightedmeans, FGBNMS_om_spp, FGBNMS_s_spp, FGBNMS_rm_spp, species_list)
     }
    
        else if (selected_region == "St Thomas, St John") {
      STTSTJ_weightedmeans <- NCRMP_STTSTJ_Occ_Den_CV
      #, YEAR == max(NCRMP_DRM_FLK_Occ_Den_CV$YEAR))
      om <- NCRMP_DRM_calculate_mortality(region = "STTSTJ", project = "NCRMP")
      STTSTJ_om_spp <- om$Domain_est_old_mort_species
      STTSTJ_rm_spp <- om$Domain_est_rec_mort_species
      
      # load species specific size - using max diameter here because DRM doesn't collect what's needed for area or volume
      # note this is not standardized by mortality though***
      s <- NCRMP_DRM_calculate_mean_colony_size(region = "STTSTJ", project = "NCRMP")
      STTSTJ_s_spp <- s$Domain_est_species
      generateCoralPlot("St Thomas, St John",selected_year, STTSTJ_weightedmeans, STTSTJ_om_spp, STTSTJ_s_spp, STTSTJ_rm_spp, species_list)
        }
    
        else if (selected_region == "St Croix") {
      STX_weightedmeans <- NCRMP_STX_Occ_Den_CV
      #, YEAR == max(NCRMP_DRM_FLK_Occ_Den_CV$YEAR))
      om <- NCRMP_DRM_calculate_mortality(region = "STX", project = "NCRMP")
      STX_om_spp <- om$Domain_est_old_mort_species
      STX_rm_spp <- om$Domain_est_rec_mort_species
      
      # load species specific size - using max diameter here because DRM doesn't collect what's needed for area or volume
      # note this is not standardized by mortality though***
      s <- NCRMP_DRM_calculate_mean_colony_size(region = "STX", project = "NCRMP")
      STX_s_spp <- s$Domain_est_species
      generateCoralPlot("St Croix",selected_year, STX_weightedmeans, STX_om_spp, STX_s_spp, STX_rm_spp, species_list)
     }
    
  
 

    
    
 
})
  
  
  output$speciesSelect <- renderUI({
    req(input$health_region)  # Require the selection of a health region

    # Determine the choices based on the selected health region
    choices <- switch(input$health_region,
                      "Southeast Florida" = c("Stephanocoenia intersepta", "Siderastrea siderea", "Orbicella faveolata", "Siderastrea radians", "Meandrina meandrites", "Pseudodiploria strigosa", "Porites divaricata", "Solenastrea hyades", "Agaricia lamarcki", "Montastraea cavernosa", "Agaricia agaricites", "Porites astreoides", "Oculina diffusa", "Colpophyllia natans", "Solenastrea bournoni", "Dichocoenia stokesii", "Porites porites", "Pseudodiploria clivosa", "Acropora cervicornis", "Agaricia fragilis", "Madracis auretenra", "Diploria labyrinthiformis", "Eusmilia fastigiata", "Orbicella franksi", "Favia fragum", "Madracis decactis", "Porites furcata", "Mycetophyllia aliciae"),
                      "Florida Keys" = c("Agaricia agaricites", "Siderastrea radians", "Porites divaricata", "Porites porites", "Helioceris cucullata", "Siderastrea siderea", "Agaricia humilis", "Porites furcata", "Eusmilia fastigiata", "Solenastrea bournoni", "Stephanocoenia intersepta", "Porites astreoides", "Agaricia lamarcki", "Orbicella franksi", "Montastraea cavernosa", "Diploria labyrinthiformis", "Agaricia fragilis", "Manicina areolata", "Orbicella faveolata", "Scolymia cubensis", "Pseudodiploria strigosa", "Porites branneri", "Dichocoenia stokesii", "Solenastrea hyades", "Orbicella annularis", "Colpophyllia natans", "Meandrina meandrites", "Oculina spp", "Madracis auretenra", "Madracis decactis", "Mycetophyllia aliciae", "Pseudodiploria clivosa", "Acropora cervicornis"),
                      "Dry Tortugas" = c("Agaricia agaricites", "Siderastrea siderea", "Orbicella faveolata", "Orbicella franksi", "Montastraea cavernosa", "Porites divaricata", "Porites porites", "Agaricia fragilis", "Porites furcata", "Pseudodiploria clivosa", "Pseudodiploria strigosa", "Mycetophyllia aliciae", "Siderastrea radians", "Stephanocoenia intersepta", "Agaricia humilis", "Eusmilia fastigiata", "Agaricia lamarcki", "Diploria labyrinthiformis", "Porites astreoides", "Dichocoenia stokesii", "Acropora cervicornis", "Colpophyllia natans", "Solenastrea bournoni", "Madracis decactis", "Meandrina meandrites", "Helioceris cucullata", "Orbicella annularis"),
                      "Flower Gardens" = c("Agaricia agaricites", "Agaricia fragilis", "Agaricia humilis", "Colpophyllia natans", "Helioceris cucullata", "Madracis auretenra", "Madracis decactis", "Meandrina meandrites", "Montastraea cavernosa", "Mussa angulosa", "Orbicella annularis", "Orbicella faveolata", "Orbicella franksi", "Porites astreoides", "Pseudodiploria strigosa", "Scolymia cubensis", "Siderastrea siderea", "Stephanocoenia intersepta", "Tubastraea coccinea"),
                      "Puerto Rico" = c("Acropora cervicornis", "Acropora palmata", "Agaricia agaricites", "Agaricia fragilis", "Agaricia grahamae", "Agaricia humilis", "Agaricia lamarcki", "Agaricia tenuifolia", "Colpophyllia natans", "Dendrogyra cylindrus", "Dichocoenia stokesii", "Diploria labyrinthiformis", "Eusmilia fastigiata", "Favia fragum", "Helioceris cucullata", "Madracis auretenra", "Madracis decactis", "Manicina areolata", "Meandrina danae", "Meandrina jacksoni", "Meandrina meandrites", "Montastraea cavernosa", "Mycetophyllia aliciae", "Mycetophyllia ferox", "Oculina diffusa", "Orbicella annularis", "Orbicella faveolata", "Orbicella franksi", "Porites astreoides", "Porites branneri", "Porites divaricata", "Porites furcata", "Porites porites", "Pseudodiploria clivosa", "Pseudodiploria strigosa", "Scolymia cubensis", "Siderastrea radians", "Siderastrea siderea", "Solenastrea bournoni", "Stephanocoenia intersepta"),
                      "St Thomas, St John" = c("Acropora cervicornis", "Acropora palmata", "Agaricia agaricites", "Agaricia fragilis", "Agaricia grahamae", "Agaricia humilis", "Agaricia lamarcki", "Agaricia tenuifolia", "Colpophyllia natans", "Dendrogyra cylindrus", "Dichocoenia stokesii", "Diploria labyrinthiformis", "Eusmilia fastigiata", "Favia fragum", "Helioceris cucullata", "Isophyllia sinuosa", "Madracis auretenra", "Madracis carmabi", "Madracis decactis", "Madracis formosa", "Manicina areolata", "Meandrina meandrites", "Montastraea cavernosa", "Mycetophyllia aliciae", "Orbicella annularis", "Orbicella faveolata", "Orbicella franksi", "Porites astreoides", "Porites colonensis", "Porites divaricata", "Porites furcata", "Porites porites", "Pseudodiploria clivosa", "Pseudodiploria strigosa", "Siderastrea radians", "Siderastrea siderea", "Solenastrea bournoni", "Stephanocoenia intersepta"),
                      "St Croix" = c("Acropora palmata", "Agaricia agaricites", "Agaricia fragilis", "Agaricia grahamae", "Agaricia humilis", "Agaricia lamarcki", "Agaricia tenuifolia", "Colpophyllia natans", "Dichocoenia stokesii", "Diploria labyrinthiformis", "Eusmilia fastigiata", "Favia fragum", "Helioceris cucullata", "Isophyllastrea rigida", "Isophyllia sinuosa", "Madracis auretenra", "Madracis decactis", "Madracis formosa", "Manicina areolata", "Meandrina meandrites", "Montastraea cavernosa", "Mycetophyllia aliciae", "Orbicella annularis", "Orbicella faveolata", "Orbicella franksi", "Porites astreoides", "Porites branneri", "Porites colonensis", "Porites divaricata", "Porites furcata", "Porites porites", "Pseudodiploria clivosa", "Pseudodiploria strigosa", "Siderastrea radians", "Siderastrea siderea", "Solenastrea bournoni", "Stephanocoenia intersepta")
    )
  
    checkboxGroupInput("speciesSelect", "Select Species:", choices)
})
  

output$bleach <- renderPlot({
  
    dataset <- switch(input$health_region,
                      "Southeast Florida" = NCRMP_DRM_SEFCRI_2014_22_ble_prev_species_region,
                      "Florida Keys" = NCRMP_DRM_FLK_2014_22_ble_prev_species_region,
                      "Dry Tortugas" = NCRMP_DRM_Tort_2014_22_ble_prev_species_region,
                      "Flower Gardens" = NCRMP_FGBNMS_2013_22_ble_prev_species_region,
                      "Puerto Rico" = NCRMP_PRICO_2014_21_ble_prev_species_region,
                      "St Thomas, St John" = NCRMP_STTSTJ_2013_21_ble_prev_species_region,
                      "St Croix" = NCRMP_STX_2015_21_ble_prev_species_region)

    dataset %>%
      filter(species_name %in% input$speciesSelect) %>%
      filter(YEAR == input$health_year) %>%
      ggplot(aes(x = reorder(species_name, avBlePrev), y = avBlePrev)) +
      geom_bar(stat = "identity", fill = "deepskyblue4") +
      geom_errorbar(aes(ymin = avBlePrev, ymax = avBlePrev + SE_B), width = 0.1) +
      coord_flip() +
      guides(fill = "none") +
      labs(y = "Bleaching Prevalence (%)", x = "", title = input$health_region) +
      scale_y_continuous(expand = c(0, 0)) +
      theme_Publication(base_size = 20) + 
      theme(axis.text.y = element_text(face = "italic"))
})


output$disease <- renderPlot({
    
    dataset <- switch(input$health_region,
                      "Southeast Florida" =  NCRMP_DRM_SEFCRI_2014_22_dis_prev_species_region,
                      "Florida Keys" = NCRMP_DRM_FLK_2014_22_dis_prev_species_region,
                      "Dry Tortugas" = NCRMP_DRM_Tort_2014_22_dis_prev_species_region,
                      "Flower Gardens" = NCRMP_FGBNMS_2013_22_dis_prev_species_region,
                      "Puerto Rico" = NCRMP_PRICO_2014_21_dis_prev_species_region,
                      "St Thomas, St John" = NCRMP_STTSTJ_2013_21_dis_prev_species_region,
                      "St Croix" = NCRMP_STX_2015_21_dis_prev_species_region)
    
    dataset %>% 
      filter(species_name %in% input$speciesSelect) %>%
      filter(YEAR == input$health_year) %>%
      ggplot(aes(x = reorder(species_name, avDisPrev), y = avDisPrev)) +
      geom_bar(stat = "identity", fill = "deepskyblue4") + 
      geom_errorbar(aes(x = reorder(species_name, avDisPrev), ymin = avDisPrev,  ymax = avDisPrev+SE_D),width = 0.1) +
      coord_flip() + 
      guides(fill = "none") +
      labs(y = "Disease Prevalence (%)", x = "", title = "Southeast Florida") + 
      scale_y_continuous(expand = c(0, 0), limits = c(0, 4.5)) +
      theme_Publication(base_size = 20) +
      theme(axis.text.y = element_text(face = "italic")) 
    
      })


    
output$dry_tortugas_plot <- renderPlot({
      
      
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("Dry Tortugas" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
      region_data <- NCRMP_Tort_2014_22_cover_region %>% dplyr::mutate(YEAR = ifelse(YEAR == 2020, 2021, as.numeric(YEAR)))
      
      generateRegionPlot(region_data, selected_years, "Dry Tortugas", selected_covers)
    }
  })
    
    
    
     output$flower_gardens_plot <- renderPlot({
      
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("Flower Gardens" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
    region_data <- NCRMP_FGBNMS_2013_22_cover_region %>% dplyr::mutate(YEAR = ifelse(YEAR == 2020, 2021, as.numeric(YEAR)))
      
      generateRegionPlot(region_data, selected_years, "Flower Gardens", selected_covers)
    }
  })
     

  output$puerto_rico_plot <- renderPlot({
      
      
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("Puerto Rico" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
      region_data <- NCRMP_PRICO_2014_21_cover_region %>% dplyr::mutate(YEAR = ifelse(YEAR == 2020, 2021, as.numeric(YEAR)))
      
      generateRegionPlot(region_data, selected_years, "Puerto Rico", selected_covers)
    }
  })
  
    output$st_thomas_st_john_plot <- renderPlot({
      
      
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("St Thomas, St John" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
      region_data <- NCRMP_STTSTJ_2013_21_cover_region %>% dplyr::mutate(YEAR = ifelse(YEAR == 2020, 2021, as.numeric(YEAR)))
      
      generateRegionPlot(region_data, selected_years, "St Thomas, St John", selected_covers)
    }
  })
    
  output$st_croix_plot <- renderPlot({
      
      
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("St Croix" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
      region_data <- NCRMP_STX_2015_21_cover_region %>% dplyr::mutate(YEAR = ifelse(YEAR == 2020, 2021, as.numeric(YEAR)))
      
      generateRegionPlot(region_data, selected_years, "St Croix", selected_covers)
    }
  })
    
  
  output$southeast_florida_plot <- renderPlot({
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("Southeast Florida" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
      region_data <- NCRMP_SEFCRI_2014_22_cover_region
      
      generateRegionPlot(region_data, selected_years, "Southeast Florida", selected_covers)
    }
  })
  
  output$florida_keys_plot <- renderPlot({
    selected_regions <- input$region
    selected_covers <- input$cover
    
    if ("Florida Keys" %in% selected_regions) {
      selected_years <- as.character(input$year[1]:input$year[2])
      
      region_data <- NCRMP_FLK_2014_22_cover_region %>% filter(YEAR != 2020)
      
      generateRegionPlot(region_data, selected_years, "Florida Keys", selected_covers)
    }
  })
}

shinyApp(ui, server)

```
